// ========================================
// ShareMySpot — Web Share API Logic
// ========================================

var Share = (function () {
  'use strict';

  function dataURLtoFile(dataURL, filename) {
    var arr = dataURL.split(',');
    var mime = arr[0].match(/:(.*?);/)[1];
    var bstr = atob(arr[1]);
    var n = bstr.length;
    var u8arr = new Uint8Array(n);
    while (n--) { u8arr[n] = bstr.charCodeAt(n); }
    return new File([u8arr], filename, { type: mime });
  }

  function buildMessage(loc) {
    return ShareMySpotShareUtils.buildCardText({
      greeting: Storage.getSettings().greeting,
      loc: loc
    });
  }

  function getLocationImages(loc) {
    return ShareMySpotShareUtils.getShareImages(loc);
  }

  function loadCanvasImage(src) {
    return new Promise(function (resolve) {
      if (!src) return resolve(null);
      var img = new Image();
      img.onload = function () { resolve(img); };
      img.onerror = function () { resolve(null); };
      img.src = src;
    });
  }

  function roundedRect(ctx, x, y, w, h, r) {
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.lineTo(x + w - r, y);
    ctx.quadraticCurveTo(x + w, y, x + w, y + r);
    ctx.lineTo(x + w, y + h - r);
    ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
    ctx.lineTo(x + r, y + h);
    ctx.quadraticCurveTo(x, y + h, x, y + h - r);
    ctx.lineTo(x, y + r);
    ctx.quadraticCurveTo(x, y, x + r, y);
    ctx.closePath();
  }

  function wrapText(ctx, text, x, y, maxWidth, lineHeight) {
    var words = String(text || '').split(' ');
    var line = '';
    for (var n = 0; n < words.length; n++) {
      var testLine = line + words[n] + ' ';
      if (ctx.measureText(testLine).width > maxWidth && n > 0) {
        ctx.fillText(line, x, y);
        line = words[n] + ' ';
        y += lineHeight;
      } else {
        line = testLine;
      }
    }
    ctx.fillText(line, x, y);
    return y + lineHeight;
  }

  async function buildCardImage(loc) {
    var images = getLocationImages(loc);
    var loaded = [];
    for (var i = 0; i < images.length; i++) loaded.push(await loadCanvasImage(images[i].dataUrl));

    var canvas = document.createElement('canvas');
    canvas.width = 1080;
    canvas.height = 1350;
    var ctx = canvas.getContext('2d');
    ctx.fillStyle = '#f6f7f8';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = '#075E54';
    roundedRect(ctx, 50, 50, 980, 220, 36);
    ctx.fill();
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 58px system-ui, -apple-system, Arial';
    ctx.fillText(loc.name || 'ShareMySpot', 90, 140);
    ctx.font = '34px system-ui, -apple-system, Arial';
    ctx.fillText('شارك موقعي • Location card', 90, 200);

    ctx.fillStyle = '#ffffff';
    roundedRect(ctx, 50, 310, 980, 250, 28);
    ctx.fill();
    ctx.fillStyle = '#111827';
    ctx.font = 'bold 42px system-ui, -apple-system, Arial';
    ctx.fillText('📍 Google Maps Location', 90, 380);
    ctx.font = '30px system-ui, -apple-system, Arial';
    wrapText(ctx, loc.mapsUrl || '', 90, 435, 900, 42);
    if (loc.doorNumber) {
      ctx.font = 'bold 36px system-ui, -apple-system, Arial';
      ctx.fillText('🚪 ' + loc.doorNumber, 90, 535);
    }

    var y = 610;
    if (loaded.length) {
      for (var j = 0; j < loaded.length; j++) {
        var x = loaded.length === 1 ? 190 : (j === 0 ? 70 : 555);
        var w = loaded.length === 1 ? 700 : 455;
        var h = 520;
        ctx.fillStyle = '#e5e7eb';
        roundedRect(ctx, x, y, w, h, 28);
        ctx.fill();
        if (loaded[j]) {
          ctx.save();
          roundedRect(ctx, x, y, w, h, 28);
          ctx.clip();
          var img = loaded[j];
          var scale = Math.max(w / img.width, h / img.height);
          var dw = img.width * scale;
          var dh = img.height * scale;
          ctx.drawImage(img, x + (w - dw) / 2, y + (h - dh) / 2, dw, dh);
          ctx.restore();
        }
      }
      y += 570;
    }

    ctx.fillStyle = '#6b7280';
    ctx.font = '28px system-ui, -apple-system, Arial';
    ctx.fillText('Generated by ShareMySpot — افتح الرابط للوصول للموقع', 70, 1280);
    return canvas.toDataURL('image/jpeg', 0.86);
  }

  async function shareLocation(locationId) {
    var loc = Storage.getLocationById(locationId);
    if (!loc) return;

    var message = buildMessage(loc);
    var shareData = { text: message };

    var images = getLocationImages(loc);
    var files = [];
    if (images.length) {
      var cardDataUrl = await buildCardImage(loc);
      files.push(dataURLtoFile(cardDataUrl, (loc.name || 'sharemyspot') + '-full-card.jpg'));
      for (var i = 0; i < images.length; i++) {
        files.push(dataURLtoFile(images[i].dataUrl, images[i].name || ('door-photo-' + (i + 1) + '.jpg')));
      }
      if (navigator.canShare && navigator.canShare({ files: files })) {
        shareData.files = files;
      } else if (navigator.canShare && navigator.canShare({ files: [files[0]] })) {
        shareData.files = [files[0]];
      }
    }

    try {
      if (!navigator.share) throw new Error('Web Share API unavailable');
      await navigator.share(shareData);
    } catch (err) {
      if (err.name !== 'AbortError') {
        // Fallback: copy to clipboard
        try {
          await navigator.clipboard.writeText(message);
          App.showToast(I18n.t('copied'));
        } catch (clipErr) {
          App.showToast(I18n.t('shareError'));
        }
      }
    }
  }

  function handleImageUpload(file) {
    return new Promise(function (resolve) {
      var reader = new FileReader();
      reader.onload = function (e) {
        var img = new Image();
        img.onload = function () {
          var canvas = document.createElement('canvas');
          var MAX_WIDTH = 800;
          var width = img.width;
          var height = img.height;
          if (width > MAX_WIDTH) {
            height = (height * MAX_WIDTH) / width;
            width = MAX_WIDTH;
          }
          canvas.width = width;
          canvas.height = height;
          canvas.getContext('2d').drawImage(img, 0, 0, width, height);
          resolve(canvas.toDataURL('image/jpeg', 0.8));
        };
        img.src = e.target.result;
      };
      reader.readAsDataURL(file);
    });
  }

  function handleImageUploads(fileList) {
    var files = Array.prototype.slice.call(fileList || []).slice(0, 2);
    return Promise.all(files.map(function (file, index) {
      return handleImageUpload(file).then(function (dataUrl) {
        return { dataUrl: dataUrl, name: file.name || ('location-' + (index + 1) + '.jpg') };
      });
    }));
  }


  async function prepareForNumber(locationId, phoneRaw) {
    var loc = Storage.getLocationById(locationId);
    if (!loc) return false;
    var url = Utils.buildWhatsAppUrl(phoneRaw, buildMessage(loc));
    if (!url) {
      App.showToast('أدخل رقم واتساب صحيح');
      return false;
    }

    var message = buildMessage(loc);
    try { await navigator.clipboard.writeText(message); } catch (err) {}

    var images = getLocationImages(loc);
    if (images.length) {
      try {
        var cardDataUrl = await buildCardImage(loc);
        var a = document.createElement('a');
        a.href = cardDataUrl;
        a.download = (loc.name || 'sharemyspot') + '-full-card.jpg';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        App.showToast('Card copied/downloaded. Opening WhatsApp...');
      } catch (err) {
        App.showToast('Message copied. Opening WhatsApp...');
      }
    } else {
      App.showToast('Message copied. Opening WhatsApp...');
    }

    setTimeout(function () { window.open(url, '_blank', 'noopener'); }, 350);
    return true;
  }

  async function copyLocation(locationId) {
    var loc = Storage.getLocationById(locationId);
    if (!loc) return;
    var message = buildMessage(loc);
    try {
      await navigator.clipboard.writeText(message);
      var images = getLocationImages(loc);
      if (images.length) {
        var cardDataUrl = await buildCardImage(loc);
        var downloads = [{ dataUrl: cardDataUrl, name: (loc.name || 'sharemyspot') + '-full-card.jpg' }].concat(images);
        for (var i = 0; i < downloads.length; i++) {
          var a = document.createElement('a');
          a.href = downloads[i].dataUrl;
          a.download = downloads[i].name || ((loc.name || 'location') + '-' + (i + 1) + '.jpg');
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
        }
        App.showToast(I18n.t('copiedWithPhoto'));
      } else {
        App.showToast(I18n.t('copied'));
      }
    } catch (err) {
      App.showToast(I18n.t('shareError'));
    }
  }

  return {
    shareLocation: shareLocation,
    prepareForNumber: prepareForNumber,
    copyLocation: copyLocation,
    handleImageUpload: handleImageUpload,
    handleImageUploads: handleImageUploads
  };
})();
